name: build

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.clang-format'
      - '.gitignore'
      - 'README.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '.clang-format'
      - '.gitignore'
      - 'README.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    #- name: install dependencies
    #  run: sudo apt-get install -y --no-install-recommends --no-install-suggests
    #       libmbedtls-dev
    - name: build
      run: CC=gcc ./build.sh --disable-test

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test
      run: CC=gcc ./build.sh test

